name: Likely
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  appinio_swiper: ^2.0.3
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.22.0
  firebase_storage: null
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  onboarding: ^3.1.0
  provider: null
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/logo/
